# Generated by Django 3.1.2 on 2020-12-06 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('url', models.TextField(verbose_name='URL')),
                ('method', models.IntegerField(verbose_name='请求方法')),
                ('request_type', models.IntegerField(verbose_name='参数类型')),
                ('request_body', models.TextField(verbose_name='参数内容')),
                ('response', models.TextField(verbose_name='结果')),
                ('response_assert', models.TextField(verbose_name='结果')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manage.module')),
            ],
        ),
    ]
